os: linux
dist: focal
language: python
virt: vm
group: edge

arch:
    - arm64-graviton2

install:
    - sudo apt-get update && sudo apt-get install cmake
    - which -a cmake
    - which -a cmake | xargs file
    - cmake --version
